### ISSUE TITLE
Is this working in a docker environment?

### ISSUE THREAD

**Issue by raLaaaa** [amahdy/vaadin-light#3]
Hey, I some how cant get this example running in docker, I always receive the following excepetion:

```
[main] INFO org.eclipse.jetty.util.log - Logging initialized @226ms to org.eclipse.jetty.util.log.Slf4jLog
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 1.8.0_111-8u111-b14-2~bpo8+1-b14
[main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@1a407d53{/,jar:file:/usr/app/jk-1.2-SNAPSHOT-jar-with-dependencies.jar!/webapp/,UNAVAILABLE}
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:438)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:355)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:173)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:102)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.server.Server.start(Server.java:418)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at io.taliox.App.main(App.java:37)
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@71e7a66b{HTTP/1.1,[http/1.1]}{0.0.0.0:9091}
[main] INFO org.eclipse.jetty.server.Server - Started @732ms
```
This exception occurs when I start my container.

This only happens in a docker environment though, if I start the App locally everything works fine. This is my dockerimage:

The way I build the .jar is simply `mvn clean package -Pproduction-mode`

```
FROM java:8
VOLUME /tmp
COPY ./target /usr/app/
WORKDIR /usr/app
RUN sh -c 'touch jk-1.2-SNAPSHOT-jar-with-dependencies.jar'
ENTRYPOINT ["java","-jar","jk-1.2-SNAPSHOT-jar-with-dependencies.jar"]  
```

Any ideas why this is not working in Docker for me? It must be somehow related to a missing / unavailable `/webapp/` folder I assume.

Is this standalone intended to work in docker? Maybe I did a mistake while importing and slightly adapting the project? :/ Thanks in advance!

**Comment by amahdy** [comment]
I haven't tried before, can you write a small script to unzip the jar file and list the file contents? Then match it with the one created locally?

In general, this is not the only way to get a Vaadin application to run in a container, you can always use a separate application server for example.

**Comment by raLaaaa** [comment]
Sorry for the late reply, have been on vacay. I'll have a look at the unzipped jar and possible differences between the local one and the automated one :)

**Comment by raLaaaa** [comment]
Update: I conducted a comparison between the local fat jar and the docker jar. Both seem to be equal, how ever the sequence of the files inside of jar is different in some cases. They are equal to 90% but some parts which are at the top of the local jar are at the bottom of the docker-jar. I don`t think how ever that this should cause any problems, right?

**Comment by amahdy** [comment]
I don't think the order matters, however, I'm not sure what is the reason of this error. All I can see is that, your docker unzip process does not create `webapp` folder for some reason. Maybe permission issue or something similar.

**Comment by raLaaaa** [comment]
I was able to solve this problem by editing things inside my dockerfile:

```
FROM openjdk:8-jre-alpine
COPY /target/ /app/
CMD ["/usr/bin/java", "-jar", "/app/jk-1.2-SNAPSHOT-jar-with-dependencies.jar"]
```

**Comment by amahdy** [comment]
Great to hear! Thanks for providing the solution.
